/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirjava;

import java.sql.Connection;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OKRAFALDINO
 */
public class booking_futsal extends javax.swing.JFrame {
    private String tgl;
    private String sql;
    private Connection con;
    private Statement stat;
    private ResultSet rs;
    int xMouse;
    int yMouse;
    

    /**
     * Creates new form booking_futsal
     */
    public booking_futsal() {
        initComponents();
        tampil_lapangan_futsal();
         getRootPane().setBorder(BorderFactory.createMatteBorder(8, 1, 8, 1, Color.gray));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framedrag = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtnotrans = new javax.swing.JTextField();
        txttanggal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtnm = new javax.swing.JTextField();
        txtlm = new javax.swing.JTextField();
        txtjammulai = new javax.swing.JTextField();
        txtjamselesai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbkdlapangan = new javax.swing.JComboBox<>();
        txthrg = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        txtdp = new javax.swing.JTextField();
        txtsisa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_input_booking_badminton = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        framedrag.setkEndColor(new java.awt.Color(0, 102, 204));
        framedrag.setkGradientFocus(600);
        framedrag.setkStartColor(new java.awt.Color(0, 0, 70));
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        framedrag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/5b06a18c18cb487b84af7955d6d905e4__2_-removebg-preview.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        framedrag.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 180, 110));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("BOOKING FUTSAL");
        framedrag.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("INPUT DATA");
        framedrag.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 30));

        getContentPane().add(framedrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("No Transaksi");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tanggal Booking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Lama");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Jam Mulai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Jam Selesai");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 20, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(":");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 20, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(":");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 20, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText(":");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 20, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText(":");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 20, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText(":");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 20, -1));
        getContentPane().add(txtnotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 30));

        txttanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txttanggalPropertyChange(evt);
            }
        });
        getContentPane().add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, 30));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, 30));
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 170, 30));
        getContentPane().add(txtlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 170, 30));
        getContentPane().add(txtjammulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));
        getContentPane().add(txtjamselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Kode Lapangan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Total");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("DP");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sisa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText(":");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 20, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 20, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText(":");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 20, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText(":");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 20, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText(":");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 20, -1));

        cmbkdlapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkdlapanganActionPerformed(evt);
            }
        });
        getContentPane().add(cmbkdlapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 170, 30));

        txthrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthrgActionPerformed(evt);
            }
        });
        getContentPane().add(txthrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 130, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-estimate-32.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 40, -1));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 170, 30));
        getContentPane().add(txtdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 130, 40));
        getContentPane().add(txtsisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 170, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-math-32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 40, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-save-32 (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-pencil-32.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-remove-32.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-broom-32.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-preview-pane-32.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-logout-30.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));

        tbl_input_booking_badminton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Transaksi", "Tanggal Booking", "Nama", "Lama Sewa", "Jam Mula1", "Jam Selesai", "Kode Lapangan", "Harga", "DP", "Sisa"
            }
        ));
        jScrollPane1.setViewportView(tbl_input_booking_badminton);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 820, 100));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/vector-JUL-2021-61 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, 40, -1, 430));

        setSize(new java.awt.Dimension(819, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_framedragMousePressed

    private void txttanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txttanggalPropertyChange
        // Tanggal
        if(txttanggal.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tgl=format.format(txttanggal.getDate());
        }

    }//GEN-LAST:event_txttanggalPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cart
        String panggil ="";
        try {
            Connection c = database.getkoneksi();
            Object st = txtnotrans.getText();
            panggil = st.toString();
            sql = "select * from tbl_booking_futsal where No_Transaksi = '" +panggil+"'";
            stat = c.createStatement();
            rs = stat.executeQuery(sql);
            while(rs.next()){
                txttanggal.setDate(rs.getDate("tgl_booking"));
                txtnm.setText(rs.getString("nama"));
                txtlm.setText(rs.getString("lama"));
                txtjammulai.setText(rs.getString("jam_mulai"));
                txtjamselesai.setText(rs.getString("jam_selesai"));
                txthrg.setText(rs.getString("harga"));
                txttotal.setText(rs.getString("total"));
                txtdp.setText(rs.getString("dp"));
                txtsisa.setText(rs.getString("sisa"));

            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Dipanggil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data tidak berhasil dipanggil");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbkdlapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkdlapanganActionPerformed
        // kode_lapangan
        Connection c=database.getkoneksi();
        try{
            Object kd = cmbkdlapangan.getSelectedItem();
            String kd_lapangan = kd.toString();
            sql="Select Harga From tbl_lapangan_futsal where kd_Lapangan = '"+kd_lapangan+"'";
            stat=c.createStatement();
            rs = stat.executeQuery(sql);
            while (rs.next())
            {
                String hargasewa = rs.getString("harga");
                txthrg.setText(hargasewa);

            }
        }catch(Exception e){JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_cmbkdlapanganActionPerformed

    private void txthrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthrgActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // hitung
        int lama , harga , total=0;
        lama = Integer.parseInt(txtlm.getText());
        harga = Integer.parseInt(txthrg.getText());
        total = lama * harga;
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // hitung  sisa
        int total = 0,dp,sisa;
        total = Integer.parseInt(txttotal.getText());
        dp = Integer.parseInt(txtdp.getText());
        sisa = total - dp;
        txtsisa.setText(String.valueOf(sisa));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // simpan
        try {
            Connection c=database.getkoneksi();
            sql="insert into tbl_booking_futsal values('"+txtnotrans.getText()+"','"
            +tgl+"','"
            +txtnm.getText()+"','"
            +txtlm.getText()+"','"
            +txtjammulai.getText()+"','"
            +txtjamselesai.getText()+"','"
            +cmbkdlapangan.getSelectedItem()+"','"
            +txthrg.getText()+"','"
            +txttotal.getText()+"','"
            +txtdp.getText()+"','"
            +txtsisa.getText()+"')";
            stat=c.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "INPUT DATA BERHASIL");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "INPUT DATA GAGAL"+e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // edit
         try {
            Connection c=database.getkoneksi();
            sql="update tbl_booking_futsal set No_Transaksi ='" +txtnotrans.getText()
                    +"',tgl_booking ='"+tgl
                    +"',nama ='"+txtnm.getText()
                    +"',lama ='"+txtlm.getText()
                    +"',jam_mulai ='"+txtjammulai.getText()
                    +"',jam_selesai ='"+txtjamselesai.getText()
                    +"',kd_lapangan ='"+cmbkdlapangan.getSelectedItem()
                    +"',harga ='"+txthrg.getText()
                    +"',total ='"+txttotal.getText()
                    +"',dp ='"+txtdp.getText()
                    +"',sisa ='"+txtsisa.getText()
                    +"'where No_Transaksi ='"+txtnotrans.getText()+"'";
            stat.execute(sql);
            stat=c.createStatement();
            JOptionPane.showMessageDialog(null,"Data berhasil diedit");
                   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Gagal mengedit data");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // hapus
        try {
            Connection c=database.getkoneksi();
            sql="delete from tbl_booking_futsal where No_Transaksi ='" +txtnotrans.getText()+"'";
            stat.execute(sql);
            stat=c.createStatement();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Gagal dihapus");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // clear
        txtnotrans.setText("");

        txtnm.setText("");
        txtlm.setText("");
        txtjammulai.setText("");
        txtjamselesai.setText("");
        txthrg.setText("");
        txttotal.setText("");
        txtdp.setText("");
        txtsisa.setText("");
        txtnotrans.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // preview
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("No");
        tableModel.addColumn("No Transaksi");
        tableModel.addColumn("Tanggal Booking");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Lama");
        tableModel.addColumn("Jam Mulai");
        tableModel.addColumn("Jam Selesai");
        tableModel.addColumn("Kode Lapangan");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Total Bayar");
        tableModel.addColumn("DP");
        tableModel.addColumn("Sisa");
        int no=1;
        try {
            Connection c=database.getkoneksi();
            sql = "select * from tbl_booking_futsal";
            Statement st=c.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                tableModel.addRow(new Object[]{(""+no++),rs.getString("No_Transaksi"),
                    rs.getString("tgl_booking"),
                    rs.getString("nama"),
                    rs.getString("lama"),
                    rs.getString("jam_mulai"),
                    rs.getString("jam_selesai"),
                    rs.getString("kd_lapangan"),
                    rs.getString("harga"),
                    rs.getString("total"),
                    rs.getString("dp"),
                    rs.getString("sisa")});

        }
        tbl_input_booking_badminton.setModel(tableModel);
        JOptionPane.showMessageDialog(null,"Berhasil Menampilkan ke Table");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // KELUAR
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking_futsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking_futsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking_futsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking_futsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking_futsal().setVisible(true);
            }
        });
    }
    private void tampil_lapangan_futsal(){
        try{
           Connection c=database.getkoneksi();
            cmbkdlapangan.addItem("=Pilih Kode Lapangan=");
            sql = "select * from tbl_lapangan_futsal";
            rs = stat.executeQuery(sql);
            stat=c.createStatement();
            while(rs.next())
            {
                String Kd_lapangan= rs.getString("kd_lapangan");
                cmbkdlapangan.addItem(Kd_lapangan);
            }
        }
        catch(Exception e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbkdlapangan;
    private keeptoo.KGradientPanel framedrag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_input_booking_badminton;
    private javax.swing.JTextField txtdp;
    private javax.swing.JTextField txthrg;
    private javax.swing.JTextField txtjammulai;
    private javax.swing.JTextField txtjamselesai;
    private javax.swing.JTextField txtlm;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnotrans;
    private javax.swing.JTextField txtsisa;
    private com.toedter.calendar.JDateChooser txttanggal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
