/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirjava;

/**
 *
 * @author OKRAFALDINO
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Dino Sport Center");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        rSButtonMetro3 = new rsbuttom.RSButtonMetro();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        rSButtonMetro8 = new rsbuttom.RSButtonMetro();
        rSButtonMetro9 = new rsbuttom.RSButtonMetro();
        rSButtonMetro10 = new rsbuttom.RSButtonMetro();
        rSButtonMetro11 = new rsbuttom.RSButtonMetro();
        desktoppane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        about = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/5b06a18c18cb487b84af7955d6d905e4__2_-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 180, 110));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4000, 50));

        jPanel3.setBackground(new java.awt.Color(239, 238, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-home-page-50.png"))); // NOI18N
        rSButtonMetro2.setText("Home");
        rSButtonMetro2.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro2.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro2.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro2.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro2.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro2.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro2.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro2.setIconTextGap(25);
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 50));

        rSButtonMetro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-soccer-ball-50.png"))); // NOI18N
        rSButtonMetro3.setText("Lapangan Futsal");
        rSButtonMetro3.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro3.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro3.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro3.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro3.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro3.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro3.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro3.setIconTextGap(25);
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 50));

        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-book-50.png"))); // NOI18N
        rSButtonMetro4.setText("Booking Futsal");
        rSButtonMetro4.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro4.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro4.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro4.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro4.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro4.setIconTextGap(25);
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 320, 50));

        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-shuttlecock-50.png"))); // NOI18N
        rSButtonMetro5.setText("Lapangan Badminton");
        rSButtonMetro5.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro5.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro5.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro5.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro5.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro5.setIconTextGap(25);
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 128, 131));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-user-48.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 0, 50, 70));

        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("_____________________________________________________");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 128, 131));
        jLabel5.setText("HELP");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 80, -1));

        jLabel6.setForeground(new java.awt.Color(128, 128, 131));
        jLabel6.setText("_____________________________________________________");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setText("Administrator");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 128, 131));
        jLabel8.setText("MASTER");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 80, -1));

        jLabel9.setForeground(new java.awt.Color(128, 128, 131));
        jLabel9.setText("_____________________________________________________");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 20));

        rSButtonMetro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-logout-rounded-50.png"))); // NOI18N
        rSButtonMetro6.setText("Logout");
        rSButtonMetro6.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro6.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro6.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro6.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro6.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro6.setIconTextGap(25);
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 320, 50));

        rSButtonMetro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-info-60.png"))); // NOI18N
        rSButtonMetro7.setText("About Me");
        rSButtonMetro7.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro7.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro7.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro7.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro7.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro7.setIconTextGap(15);
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 320, 50));

        rSButtonMetro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-online-payment-50.png"))); // NOI18N
        rSButtonMetro8.setText("Pembayaran");
        rSButtonMetro8.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro8.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro8.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro8.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro8.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro8.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro8.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro8.setIconTextGap(25);
        rSButtonMetro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro8ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 320, 50));

        rSButtonMetro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-add-bookmark-50.png"))); // NOI18N
        rSButtonMetro9.setText("Booking Badminton");
        rSButtonMetro9.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro9.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro9.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro9.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro9.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro9.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro9.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro9.setIconTextGap(25);
        rSButtonMetro9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro9ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 320, 50));

        rSButtonMetro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-terms-and-conditions-50 (1).png"))); // NOI18N
        rSButtonMetro10.setText("Laporan Booking");
        rSButtonMetro10.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro10.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro10.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro10.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro10.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro10.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro10.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro10.setIconTextGap(25);
        rSButtonMetro10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro10ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 320, 50));

        rSButtonMetro11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/icons8-business-report-50.png"))); // NOI18N
        rSButtonMetro11.setText("Laporan Pembayaran");
        rSButtonMetro11.setColorBorde(new javax.swing.border.MatteBorder(null));
        rSButtonMetro11.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro11.setColorNormal(new java.awt.Color(239, 238, 244));
        rSButtonMetro11.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro11.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro11.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro11.setColorTextPressed(new java.awt.Color(128, 128, 131));
        rSButtonMetro11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro11.setIconTextGap(25);
        rSButtonMetro11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro11ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 320, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 320, 4000));

        desktoppane.setBackground(new java.awt.Color(255, 255, 255));
        desktoppane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/pngwing.com (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4000, 1000));

        jTabbedPane1.addTab("tab1", home);

        about.setBackground(new java.awt.Color(0, 0, 0));
        about.setPreferredSize(new java.awt.Dimension(4000, 1002));
        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambaricon/5b06a18c18cb487b84af7955d6d905e4__2_-removebg-preview.png"))); // NOI18N
        jLabel14.setText("jLabel1");
        about.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 180, 110));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("OKRAFALDINO");
        about.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 112, 130, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jln.Rawang Ketaping No.26 ,Padang , Sumatera Barat");
        about.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 80, 350, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("____________________________________");
        about.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 370, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BY");
        about.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4000, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        about.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4000, 1000));

        jTabbedPane1.addTab("tab2", about);

        desktoppane.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 4000, 1030));

        getContentPane().add(desktoppane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 3980, 4000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // logout
        dispose();
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        // about
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        new pembayaran().show();;
                
    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // Home
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        // Input data lapangan futsal
        new input_lapangan_futsal().show();
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void rSButtonMetro9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro9ActionPerformed
        // Booking badmintoon
        new booking_badminton().show();
    }//GEN-LAST:event_rSButtonMetro9ActionPerformed

    private void rSButtonMetro10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro10ActionPerformed
        new lap_lapangan().show();
        
    }//GEN-LAST:event_rSButtonMetro10ActionPerformed

    private void rSButtonMetro11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro11ActionPerformed
        new lap_pembayaran().show();
    }//GEN-LAST:event_rSButtonMetro11ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // lapangan badminton
        new input_lapangan_badminton().show();
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // booking Futsal
        new booking_futsal().show();
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about;
    private javax.swing.JPanel desktoppane;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private rsbuttom.RSButtonMetro rSButtonMetro10;
    private rsbuttom.RSButtonMetro rSButtonMetro11;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    private rsbuttom.RSButtonMetro rSButtonMetro8;
    private rsbuttom.RSButtonMetro rSButtonMetro9;
    // End of variables declaration//GEN-END:variables
}
